version: "3"
services:
  app:
    build:
      args:
        user: marketplace
        uid: 1000
      context: ./
      dockerfile: ./.docker/Dockerfile
    image: marketplace
    container_name: marketplace-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./marketplace/:/var/www
    networks:
      - marketplace

  nginx:
    image: nginx:alpine
    container_name: marketplace-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./marketplace/:/var/www
      - ./.docker/nginx/:/etc/nginx/conf.d/
    networks:
      - marketplace

  mysql8.0:
    image: mysql:8.0
    container_name: marketplace-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: marketplace
    volumes:
      - ./.docker/db/:/var/lib/mysql
    ports:
      - 3366:3306
    networks:
      - marketplace       

  redis:
    container_name: marketplace-redis
    image: redis:alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - './.docker/redis:/data'
    networks:
      - marketplace
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s


  search:
    container_name: marketplace-search
    image: elasticsearch:6.8.1
    restart: unless-stopped
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
    ports:
      - 9200:9200
    networks:
      - marketplace

networks:
  marketplace:
    driver: bridge
